<?php
     require_once('settings.php');
     $date=date('Y-m-d');
     $time=date('Y-m-d H:i:s');    
$array = ['Aalborg (AAL)',
    'Aalesund (AES)',
    'Aarhus (AAR)',
    'Aberdeen (ABZ)',
    'Abha (AHB)',
    'Abidjan (ABJ)',
    'Abilene (ABI)',
    'Abu Dhabi (ZVJ)',
    'Accra (ACC)',
    'Adana (ADA)',
    'Addis Ababa (ADD)',
    'Adelaide (ADL)',
    'Adler-Sochi (AER)',
    'Agartala (IXA)',
    'Ahmedabad (AMD)',
    'Al Ain (ZVH)',
    'Al Najaf International Airport (NJf)',
    'Albany (ALB)',
    'Albenga (ALL)',
    'Albuquerque (ABQ)',
    'Albury (ABX)',
    'Aleppo (ALP)',
    'Alexandria (HBE)',
    'Alghero (AHO)',
    'Algiers (ALG)',
    'Alicante (ALC)',
    'Alice Springs (ASP)',
    'Allahabad (IXD)',
    'Almaty (ALA)',
    'Almeria (LEI)',
    'Alor Setar (AOR)',
    'Amman (AMM)',
    'Amritsar (ATQ)',
    'Amsterdam Schiphol (AMS)',
    'Anapa (AAQ)',
    'Anchorage (ANC)',
    'Ancona (AOI)',
    'Ankara (ESB)',
    'Antalya (AYT)',
    'Aracaj (AJU)',
    'Armidale (ARM)',
    'Aruba (AUA)',
    'Asheville (AVL)',
    'Astrakhan (ASF)',
    'Asyut (ATZ)',
    'Athens (ATH)',
    'Atlanta (ATL)',
    'Auckland (AKL)',
    'Aurangabad (IXU)',
    'Austin (AUS)',
    'Avalon (AVV)',
    'Ayers Rock (AYQ)',
    'Badajoz (BJZ)',
    'Baden Baden (FKB)',
    'Baghdad (BGW)',
    'Bahrain (BAH)',
    'Baku (GYD)',
    'Ballina (BNK)',
    'Baltimore (BWI)',
    'Bangkok (BKK)',
    'Bangor (BGR)',
    'Banmethuot (BMV)',
    'Barcaldine (BCI)',
    'Barcelona (BCN)',
    'Bari (BRI)',
    'Barnaul (BAX)',
    'Basra (BSR)',
    'Beira (BEW)',
    'Belfast (BHD)',
    'Belgrade (BEG)',
    'Bellingham (BLI)',
    'Bengaluru (Bangalore) (BLR)',
    'Bermuda (BDA)',
    'Bhopal (BHO)',
    'Bilbao (BIO)',
    'Billund Airport (BLL)',
    'Biloela (ZBL)',
    'Birmingham (BHX)',
    'Blackall (BKQ)',
    'Blantyre (BLZ)',
    'Bologna (BLQ)',
    'Bolzano (BZO)',
    'Bordeaux (BOD)',
    'Brasilia (BSB)',
    'Bratsk (BTK)',
    'Brisbane (BNE)',
    'Bucharest (OTP)',
    'Buenos Aires (EZE)',
    'Buffalo (BUF)',
    'Bundaberg (BDB)',
    'Buraidah (ELQ)',
    'Burbank (BUR)',
    'Bursa (BTZ)',
    'Cagliari (CAG)',
    'Cairns (CNS)',
    'Cairo (CAI)',
    'Calgary (YYC)',
    'Cali (CLO)',
    'Campo Grande (CGR)',
    'Canberra (CBR)',
    'Cancun (CUN)',
    'Cape Town (CPT)',
    'Caracas (CCS)',
    'Cardiff (CWL)',
    'Casablanca (CMN)',
    'Catania (CTA)',
    'Chandigarh (IXC)',
    'Changsha (CSX)',
    'Chania (CHQ)',
    'Charleston (CRW)',
    'Charlestown (CHS)',
    'Charleville (CTL)',
    'Charlotte (CLT)',
    'Charlottesville (CHO)',
    'Chelyabinsk (CEK)',
    'Chennai (MAA)',
    'Chiang Mai (CNX)',
    'Chiang Rai (CEI)',
    'Chicago (ORD)',
    'Chihuahua (CUU)',
    'Cincinnati (CVG)',
    'Clark International (CRK)',
    'Cleveland (CLE)',
    'Coffs Harbour (CFS)',
    'Coimbatore (CJB)',
    'Columbia (CAE)',
    'Copenhagen (CPH)',
    'Cuiab (CGB)',
    'Curitiba (CWB)',
    'Da Nang (DAD)',
    'Dakar (DKR)',
    'Dalaman (DLM)',
    'Dalat (DLI)',
    'Dalian (DLC)',
    'Dallas (DFW)',
    'Damascus (DAM)',
    'Dammam (DMM)',
    'Dammam Sabtco bus station (DMS)',
    'Dar Es Salaam (DAR)',
    'Darwin (DRW)',
    'Dayton (DAY)',
    'Denpasar (DPS)',
    'Dhaka (DAC)',
    'Diyarbakir (DIY)',
    'Doha (DOH)',
    'Dubai (DXB)',
    'Durban (DUR)',
    'East London (ELS)',
    'Ekaterinburg (SVX)',
    'El Paso (ELP)',
    'Emerald (EMD)',
    'Ercan (ECN)',
    'Fairbanks (FAI)',
    'Faro (FAO)',
    'Fayetteville (XNA)',
    'Florianpolis (FLN)',
    'Fort Lauderdale (FLL)',
    'Fortaleza (FOR)',
    'Foz do Iguau (IGU)',
    'Frankfurt (FRA)',
    'Fresno (FAT)',
    'Fuerteventura (FUE)',
    'Fukuoka (FUK)',
    'Funchal (FNC)',
    'Gaziantep (GZT)',
    'Gdansk (GDN)',
    'Geneva (GVA)',
    'Genoa (GOA)',
    'Geraldton (GET)',
    'Gladstone (GLT)',
    'Glasgow (GLA)',
    'Goa (GOI)',
    'Goinia (GYN)',
    'Gold Coast (OOL)',
    'Gran Canaria (LPA)',
    'Granada (GRX)',
    'Guadalajara (GDL)',
    'Guangzhou (CAN)',
    'Guiyang (KWE)',
    'Guwahati (GAU)',
    'Haikou (HAK)',
    'Hail (HAS)',
    'Haiphong (HPH)',
    'Halifax (YHZ)',
    'Hamburg (HAM)',
    'Hamilton Island (HTI)',
    'Hangzhou (HGH)',
    'Hanoi (HAN)',
    'Hanover (HAJ)',
    'Harare (HRE)',
    'Harbin (HRB)',
    'Harrisburg (MDT)',
    'Hartford (BDL)',
    'Hat Yai (HDY)',
    'Hatay (HTY)',
    'Havana (HAV)',
    'Heraklion (HER)',
    'Hervey Bay (HVB)',
    'Hobart (HBA)',
    'Horn Island (HID)',
    'Houston (IAH)',
    'Hyderabad (HYD)',
    'Ibiza (IBZ)',
    'Indianapolis (IND)',
    'Islamabad (ISB)',
    'Isle of Man (IOM)',
    'Istanbul (IST)',
    'Ixtapa (ZIH)',
    'Izmir (ADB)',
    'Jacksonville (JAX)',
    'Jaipur (JAI)',
    'Jakarta (CGK)',
    'Jeddah (JED)',
    'Jerez De La Fron (XRY)',
    'Jizan (JIZ)',
    'Johannesburg (JNB)',
    'Johor Bahru (JHB)',
    'Joo Pessoa (JPA)',
    'Juneau (JNU)',
    'Kahului (OGG)',
    'Kalgoorlie (KGI)',
    'Kaliningrad (KGD)',
    'Kansas City (MCI)',
    'Karachi (KHI)',
    'Karratha (KTA)',
    'Kasane (BBK)',
    'Kathmandu (KTM)',
    'Kauai Island (LIH)',
    'Kayseri (ASR)',
    'Kazan (Ka San) (KZN)',
    'Kelowna (YLW)',
    'Ketchikan (KTN)',
    'Khabarovsk (KHV)',
    'Kharkiv (HRK)',
    'Khartoum (KRT)',
    'Khon Kaen (KKC)',
    'Koh Samui (USM)',
    'Kolkata (Calcutta) (CCU)',
    'Kona (KOA)',
    'Konya (KYA)',
    'Kota Kinabalu (BKI)',
    'Kozhikode (Calicut) (CCJ)',
    'Krabi (KBV)',
    'Krakow (KRK)',
    'Krasnodar (KRR)',
    'Krasnoyarsk Yemelyanovo (KJA)',
    'Kristiansand (KRS)',
    'Kuala Lumpur (KUL)',
    'Kuwait (KWI)',
    'La Coruna (LCG)',
    'Lafayette (LFT)',
    'Lagos (LOS)',
    'Lahore (LHE)',
    'Lamezia Terme (SUF)',
    'Lampang (LPT)',
    'Langkawi (LGK)',
    'Lanzarote (ACE)',
    'Lanzhou (LHW)',
    'Larnaca (LCA)',
    'Las Vegas (LAS)',
    'Latakia (LTK)',
    'Launceston (LST)',
    'Learmonth (LEA)',
    'London Gatwick (LGW)',
    'London Heathrow (LHR)',
    'Londrina (LDB)',
    'Long Beach (LGB)',
    'Longreach (LRE)',
    'Lord Howe Island (LDH)',
    'Los Angeles (LAX)',
    'Luanda (LAD)',
    'Luoyang (LYA)',
    'Lusaka (LUN)',
    'Macei (MCZ)',
    'Mackay (MKY)',
    'Madrid (MAD)',
    'Madurai (IXM)',
    'Malaga (AGP)',
    'Malatya (MLX)',
    'Male (MLE)',
    'Malta (MLA)',
    'Manaus (MAO)',
    'Manchester (MAN)',
    'Manchester (MHT)',
    'Manila (MNL)',
    'Manzanillo (ZLO)',
    'Marrakech (RAK)',
    'Marseille (MRS)',
    'Maseru (MSU)',
    'Mauritius (MRU)',
    'Mazatlan (MZT)',
    'Medina (Madinah)(MED)',
    'Melilla (MLN)',
    'Menorca (MAH)',
    'Miami (MIA)',
    'Milan (MXP)',
    'Mildura (MQL)',
    'Milwaukee (MKE)',
    'Minneapolis (MSP)',
    'Mnster Osnabrck (FMO)',
    'Mombasa (MBA)',
    'Montego Bay (MBJ)',
    'Montreal (YUL)',
    'Moranbah (MOV)',
    'Mount Hotham (MHU)',
    'Mount Isa (ISA)',
    'Mumbai (BOM)',
    'Murcia (MJV)',
    'Muscat (MCT)',
    'Myrtle Beach (MYR)',
    'Nadym (NYM)',
    'Nagoya (BUS) (NGY)',
    'Nagpur (NAG)',
    'Nairobi (NBO)',
    'Nampula (APL)',
    'Nanchang (KHN)',
    'Nanjing (NKG)',
    'Nanning (NNG)',
    'Naples (NAP)',
    'Nashville (BNA)',
    'Nassau (NAS)',
    'Natal (NAT)',
    'New Orleans (MSY)',
    'Newark (EWR)',
    'Newcastle (NCL)',
    'Newcastle (NTL)',
    'Newman (ZNE)',
    'Nha Trang (NHA)',
    'Nizhnevartovsk (NJC)',
    'Oakland (OAK)',
    'Oklahoma City (OKC)',
    'Olympic Dam (OLP)',
    'Orlando (MCO)',
    'Osaka (KIX)',
    'Ottawa (YOW)',
    'Palermo (PMO)',
    'Palma De Mallorc (PMI)',
    'Pamplona (PNA)',
    'Panama City (PTY)',
    'Paraburdoo (PBO)',
    'Paris (CDG)',
    'Pasco (PSC)',
    'Patna (PAT)',
    'Penang (PEN)',
    'Perm Oblast (PEE)',
    'Pescara (PSR)',
    'Peshawar (PEW)',
    'Philadelphia (PHL)',
    'Pisa (PSA)',
    'Port Elizabeth (PLZ)',
    'Port Hedland (PHE)',
    'Port Macquarie (PQQ)',
    'Portland (PDX)',
    'Porto Alegre (POA)',
    'Poznan (POZ)',
    'Prague (PRG)',
    'Pullman (PUW)',
    'Qingdao (TAO)',
    'Rach Gia (VKG)',
    'Raipur (RPR)',
    'Rajkot (RAJ)',
    'Raleigh (RDU)',
    'Ranchi (IXR)',
    'Reggio Calabria (REG)',
    'Regina (YQR)',
    'Ribeiro Preto (RAO)',
    'Richards Bay (RCB)',
    'Rio de Janeiro (GIG)',
    'Riyadh (RUH)',
    'Roanoke (ROA)',
    'Rockhampton (ROK)',
    'Roma (AU) (RMA)',
    'Sacremento (SMF)',
    'Salalah (SLL)',
    'Salt Lake City (SLC)',
    'Salvador (SSA)',
    'Samara (KUF)',
    'Samsun (SSX)',
    'San Diego (SAN)',
    'San Francisco (SFO)',
    'San Jose (SJC)',
    'San Juan (SJU)',
    'San Luis Potosi (SLP)',
    'San Sebastian (EAS)',
    'Sanaa (SAH)',
    'Sandakan (SDK)',
    'Sanliurfa (GNY)',
    'Santa Cruz (SRZ)',
    'Santa Cruz De La (SPC)',
    'Santander (SDR)',
    'Santiago De Comp (SCQ)',
    'Sanya (SYX)',
    'Sapporo (CTS)',
    'Sarasota (SRQ)',
    'Seattle (SEA)',
    'Sevilla (SVQ)',
    'Shanghai (PVG)',
    'Shantou (SWA)',
    'Shenyang (SHE)',
    'Singapore (SIN)',
    'So Paulo (GRU)',
    'Sofia (SOF)',
    'Spokane (GEG)',
    'Srinagar (SXR)',
    'Stavanger (SVG)',
    'Stockholm (ARN)',
    'Stuttgart (STR)',
    'Sukhothai (THS)',
    'Sulaymaniyah (ISU)',
    'Sunshine Coast (MCY)',
    'Ta’if (TIF)',
    'Tabuk (TUU)',
    'Tampa (TPA)',
    'Tamworth (TMW)',
    'Tehran (IKA)',
    'Thessaloniki (SKG)',
    'Thiruvananthapuram (Trivandrum) (TRV)',
    'Tianjin (TSN)',
    'Tirana (TIA)',
    'Tiruchirapally (TRZ)',
    'Tokyo All (TYO)',
    'Tokyo Haneda (HND)',
    'Tokyo Narita (NRT)',
    'Trabzon (TZX)',
    'Trat (TDX)',
    'Tulsa (TUL)',
    'Uberlndia (UDI)',
    'Ubon Ratchathani (UBP)',
    'Udaipur (UDR)',
    'Udon Thani (UTH)',
    'Ufa (UFA)',
    'Ulan-Ude (UUD)',
    'Vadodara (BDQ)',
    'Valencia (VLC)',
    'Vancouver (YVR)',
    'Varanasi (VNS)',
    'Varna (VAR)',
    'Verona (VRN)',
    'Victoria (YYJ)',
    'Vienna (VIE)',
    'Vitoria Airport (VIT)',
    'Vitria (VIX)',
    'Vladikavkaz (OGZ)',
    'Vladivostok (VVO)',
    'Volgograd (VOG)',
    'Wagga Wagga (WGA)',
    'Walla Walla (ALW)',
    'Warsaw (WAW)',
    'Washington (DCA)',
    'Washington (IAD)',
    'Weipa (WEI)',
    'Wenatchee (EAT)',
    'Wroclaw (WRO)',
    'Wuhan (WUH)',
    'Xiamen (XMN)',
    'Xian Xiguan Airport (SIA)',
    'Yakima (YKM)',
    'Yakutsk (YKS)',
    'Yaound (NSI)',
    'Zaragoza (ZAZ)'];

for($i=0;$i<count($array);$i++){
    
    $sql = "INSERT INTO `port_name` (`created`, `created_time`, `port`)
        VALUES ('".$date."','".$time."','".$array[$i]."')";
	$res = $conn->query($sql);
 
}